### ISSUE TITLE
Cardano 10.1 changes cli syntax

### ISSUE THREAD

**Issue by frog357** [Kirael12/Cardano-KES-Rotate-Companion#1]
Just tried to rotate my keys on a node running 10.1 and I noticed a few errors indicating incorrect usage of Cardano cli. They changed the top level of some commands upstream. We need this new version to enter chang-2.

cardano-cli --version
cardano-cli 10.1.0.0 - linux-x86_64 - ghc-8.10
git rev 4184f9297bf7306713bfbb8f39eef61c056198cc

**Comment by frog357** [comment]
When running the script this appears:
---------------------------------------------------------------------
 KES KEYS PERIOD AND COUNTER VALUE
---------------------------------------------------------------------

Invalid argument `query'

Usage: cardano-cli
                     ( address
                     | key
                     | node
                     | legacy
                     | byron
                     | shelley
                     | allegra
                     | mary
                     | alonzo
                     | babbage
                     | conway
                     | latest
                     | hash
                     | ping
                     | debug commands
                     | version
                     | compatible
                     )

Invalid argument `query'

**Comment by Kirael12** [comment]
Hello,

Yes. The correct syntax is now "cardano-cli conway query ..."

i'll make the change :)

**Comment by Kirael12** [comment]
Done.
